user1 = User.create(name: "Mickey Mouse", email: "mickey@dizney.com", password: "password1", password_confirmation: "password1")
user2 = User.create(name: "Minnie Mouse", email: "minnie@dizney.com", password: "password2", password_confirmation: "password2")
user3 = User.create(name: "Donald Duck", email: "donald@dizney.com", password: "password3", password_confirmation: "password3")
user4 = User.create(name: "Daisy Duck", email: "daisy@dizney.com", password: "password4", password_confirmation: "password4")
user5 = User.create(name: "Goofy", email: "goofy@dizney.com", password: "password5", password_confirmation: "password5")
user6 = User.create(name: "Pluto", email: "pluto@dizney.com", password: "password6", password_confirmation: "password6")
user7 = User.create(name: "Chip", email: "chip@dizney.com", password: "password7", password_confirmation: "password7")
user8 = User.create(name: "Dale", email: "dale@dizney.com", password: "password8", password_confirmation: "password8")
user9 = User.create(name: "Buzz Lightyear", email: "notatoy@dizney.com", password: "password9", password_confirmation: "password9")
user10 = User.create(name: "Sheriff Woody", email: "reach4thesky@dizney.com", password: "password10", password_confirmation: "password10")


location1 = Location.create(user_id: user1.id, name: "The Well Coffee House", address: "1 State Street", city: "Boston", state: "MA", zip: "02111", price: 1000, password_protected: true)
location2 = Location.create(user_id: user1.id, name: "Boston Athenaeum", address: "10 ½ Beacon Street", city: "Boston", state: "MA", zip: "02108", price: 500, password_protected: true)
location3 = Location.create(user_id: user1.id, name: "Boston Public Library", address: "700 Boylston Street", city: "Boston", state: "MA", zip: "02116")
location4 = Location.create(user_id: user2.id, name: "Thinking Cup", address: "236 Hanover Street", city: "Boston", state: "MA", zip: "02113")
location5 = Location.create(user_id: user2.id, name: "Ogawa Coffee", address: "10 Milk Street", city: "Boston", state: "MA", zip: "02108")
location6 = Location.create(user_id: user2.id, name: "Tradesman Coffee Shop and Lounge", address: "58 Batterymarch Street", city: "Boston", state: "MA", zip: "02110")
location7 = Location.create(user_id: user2.id, name: "Caffe Nero", address: "560 Washington Street", city: "Boston", state: "MA", zip: "02111")
location8 = Location.create(user_id: user1.id, name: "La Colombe Coffee Roasters", address: "29 Northern Avenue", city: "Boston", state: "MA", zip: "02210", price: 800, password_protected: true)
location9 = Location.create(user_id: user1.id, name: "Flour Bakery + Cafe", address: "131 Clarendon Street", city: "Boston", state: "MA", zip: "02116")
location10 = Location.create(user_id: user3.id, name: "Tatte Bakery & Cafe", address: "399 Boylston Street", city: "Boston", state: "MA", zip: "02116")
location11 = Location.create(user_id: user3.id, name: "Café 26", address: "26 Temple Street", city: "Boston", state: "MA", zip: "02111")
location12 = Location.create(user_id: user3.id, name: "Thinking Cup", address: "85 Newbury Street", city: "Boston", state: "MA", zip: "02116")
location13 = Location.create(user_id: user3.id, name: "Render Coffee", address: "121 Devonshire Street", city: "Boston", state: "MA", zip: "02109")


Review.create(rating: 5, body: "Great place", speed_data: "100", user_id: user1.id, location_id: location1.id)
Review.create(rating: 4, body: "Good environment", speed_data: "50", user_id: user1.id, location_id: location2.id)
Review.create(rating: 4, speed_data: "60", user_id: user1.id, location_id: location3.id)
Review.create(rating: 5, body: "My favorite place!", speed_data: "90", user_id: user1.id, location_id: location4.id)
Review.create(rating: 4, body: "Good coffee", speed_data: "30", user_id: user2.id, location_id: location1.id)
Review.create(rating: 5, speed_data: "40", user_id: user2.id, location_id: location2.id)
Review.create(rating: 5, body: "Great service, good workspace", speed_data: "40", user_id: user2.id, location_id: location3.id)
Review.create(rating: 2, body: "Poor service", speed_data: "60", user_id: user2.id, location_id: location4.id)
Review.create(rating: 1, body: "Noisy", speed_data: "50", user_id: user3.id, location_id: location5.id)
Review.create(rating: 1, body: "Poor service", speed_data: "100", user_id: user3.id, location_id: location6.id)
Review.create(rating: 1, body: "Too loud", speed_data: "10000", user_id: user3.id, location_id: location7.id)
Review.create(rating: 1, body: "Hate this place", speed_data: "30", user_id: user3.id, location_id: location8.id)
Review.create(rating: 4, body: "Good spot", speed_data: "45", user_id: user4.id, location_id: location5.id)
Review.create(rating: 3, body: "Just ok", speed_data: "50", user_id: user4.id, location_id: location6.id)
Review.create(rating: 5, body: "My favorite place!", speed_data: "60", user_id: user4.id, location_id: location7.id)
Review.create(rating: 5, body: "Best coffee!", speed_data: "90", user_id: user4.id, location_id: location8.id)
Review.create(rating: 4, body: "Good eats", speed_data: "30", user_id: user5.id, location_id: location9.id)
Review.create(rating: 5, body: "Great service!", speed_data: "25", user_id: user5.id, location_id: location10.id)
Review.create(rating: 5, body: "Good spot to work", speed_data: "100", user_id: user5.id, location_id: location11.id)
Review.create(rating: 3, body: "Just ok", speed_data: "90", user_id: user5.id, location_id: location12.id)
Review.create(rating: 2, body: "Bleh", speed_data: "40", user_id: user6.id, location_id: location9.id)
Review.create(rating: 3, body: "Just ok", speed_data: "10", user_id: user6.id, location_id: location10.id)
Review.create(rating: 4, body: "Average service, but good spot to work", speed_data: "50", user_id: user6.id, location_id: location11.id)
Review.create(rating: 5, user_id: user6.id, location_id: location12.id)
Review.create(rating: 2, body: "Terrible WiFi", speed_data: "10", user_id: user7.id, location_id: location13.id)
Review.create(rating: 4, body: "Great service", speed_data: "80", user_id: user7.id, location_id: location1.id)
Review.create(rating: 5, body: "The best coffee in Boston", user_id: user7.id, location_id: location2.id)
Review.create(rating: 5, speed_data: "1000", user_id: user7.id, location_id: location3.id)
Review.create(rating: 4, body: "I love their food", speed_data: "100", user_id: user8.id, location_id: location6.id)
Review.create(rating: 5, body: "Good coffee, great service", user_id: user8.id, location_id: location5.id)
Review.create(rating: 4, body: "Good work enviroment", user_id: user8.id, location_id: location3.id)
Review.create(rating: 5, body: "My favorite place in Boston", speed_data: "40", user_id: user8.id, location_id: location11.id)
Review.create(rating: 1, body: "Terrible lighting, even worse coffee", user_id: user9.id, location_id: location13.id)
Review.create(rating: 2, body: "Do not go there!", user_id: user9.id, location_id: location9.id)
Review.create(rating: 4, body: "Friendly staff", speed_data: "25", user_id: user9.id, location_id: location7.id)
Review.create(rating: 5, body: "I do my best work here", speed_data: "100", user_id: user9.id, location_id: location3.id)
Review.create(rating: 4, body: "Great spot", speed_data: "250", user_id: user10.id, location_id: location7.id)
Review.create(rating: 4, body: "Great place", user_id: user10.id, location_id: location8.id)
Review.create(rating: 4, speed_data: "100", user_id: user10.id, location_id: location6.id)
Review.create(rating: 4, body: "Good coffee", speed_data: "50", user_id: user10.id, location_id: location4.id)
